### ISSUE TITLE
wrong initial state

### ISSUE THREAD

**Issue by nisnardi** [eggheadio/egghead-angularjs-from-scratch-getting-started#1]
Hi, I started to watch the egghead AngularJS App From Scratch: Getting Started. I downloaded the code and the index.start.html and app.start.js files are not the same as the one in the video (AngularJS App From Scratch: Getting Started). Not sure if it's a bug but it might be confusing for someone that starts working with angular. Hope this helps. Thanks for the videos.

**Comment by jepek** [comment]
https://github.com/eggheadio/egghead-angularjs-from-scratch-getting-started/releases here you can find code step by step

**Comment by nisnardi** [comment]
Thanks

**Comment by kunalchawla** [comment]
Thanks for this comment. @jepek Thank you for the step by step for the code. That worked for me.
