### ISSUE TITLE
final html, initial html 

### ISSUE THREAD

**Issue by mesokalos** [eggheadio/egghead-angularjs-from-scratch-getting-started#2]
The html files don't actually work in the browser the way they do in the videos, these are the screens I get,
![screen shot 2014-08-21 at 3 52 38 pm](https://cloud.githubusercontent.com/assets/7890362/4002451/edb54532-296c-11e4-95c0-2520a55006d6.png)
![screen shot 2014-08-21 at 3 52 47 pm](https://cloud.githubusercontent.com/assets/7890362/4002453/edb8e6ba-296c-11e4-894c-ba1dae3fb56b.png)
![screen shot 2014-08-21 at 3 52 55 pm](https://cloud.githubusercontent.com/assets/7890362/4002452/edb62b96-296c-11e4-8d80-6b0bfca1ca85.png)

**Comment by jepek** [comment]
You have to run this on the server eg. localhost

**Comment by ashryanbeats** [comment]
For anyone looking, I had the same issue and had to get help. Let me share what I learned.

Using [`http-server`](https://www.npmjs.com/package/http-server) was the solution for me. (You'll need `npm` installed globally for this.)

```
npm install -g http-server
```

After installing `http-server`, in your terminal `cd` into the local directory for this repo. From there, you can run `http-server` in the command line.

If you have a document called `index.html`, you can just enter the command by itself:

```
http-server
```

Then in your browser go to `localhost:8080` and you should see the site running.

However, this Eggly tutorial doesn't have an `index.html` so you'll need to make one or rename one of the existing files. 

`http-server` may provide a way to run the site from another file (like, `index.complete.html`), but I'm not aware of how to do that.

Hope this helps!

**Comment by justinjdickow** [comment]
you can use

```
http-server -o
```

to open the browser after the http server starts and you will see an index of the files. From there you can select `index.complete.html`, etc.

**Comment by theianjones** [comment]
These are great solutions, I personally use live-server or httpster!

`npm install -g live-server`
or
`npm install -g httpster`
