### ISSUE TITLE
Normalize CSS hgroup Error

### ISSUE THREAD

**Issue by JimLynchCodes** [eggheadio/egghead-angularjs-from-scratch-getting-started#22]
When I copy normalize.css into my IDE (Webstorm) it complains that it can't find hgroup.
![screen shot 2016-01-09 at 7 27 32 pm](https://cloud.githubusercontent.com/assets/5354163/12219219/78fa9a7e-b707-11e5-928b-e0585556c12f.png)

**Comment by JimLynchCodes** [comment]
ok. I realize now that the hgroup error in Webstorm is because 'hgroup' was taken out of the spec in HTML5. 

But what is the recommended action to fix this is you do want to use HTML5 (and also if you want to drop back to an older HTML version)?

**Comment by theianjones** [comment]
Hey @JimTheMan this doesnt seem like an issue with the course itself.
