### ISSUE TITLE
Current category of a new bookmark is not set

### ISSUE THREAD

**Issue by WillTaylor22** [eggheadio/egghead-angularjs-from-scratch-getting-started#3]
Should be:
function createBookmark(bookmark){
        bookmark.id = $scope.bookmarks.length;
        bookmark.category = currentCategory; // <-----
        $scope.bookmarks.push(bookmark);

```
    resetCreateForm();
  }
```

**Comment by chrislerum** [comment]
Actually the line:
bookmark.category = currentCategory;
should be
bookmark.category = currentCategory.name;

**Comment by arribajuan** [comment]
The line should be:

bookmark.category = $scope.currentCategory.name;

**Comment by theianjones** [comment]
The example code should be updated with `bookmark.category = $scope.currentCategory.name;`. ([line 58 here](https://github.com/eggheadio/egghead-angularjs-from-scratch-getting-started/blob/master/app/eggly-app.finish.js))
