### ISSUE TITLE
Does not remove "active" class from edited bookmark after edit is closed out of

### ISSUE THREAD

**Issue by WillTaylor22** [eggheadio/egghead-angularjs-from-scratch-getting-started#4]
Should be:

function startCreating() {
        $scope.isCreating = true;
        $scope.isEditing = false;
        $scope.editedBookmark = null; // <----
      }

and:

function cancelEditing() {
        $scope.isEditing = false;
        $scope.editedBookmark = null; // <----
      }

Thanks for the course!

**Comment by theianjones** [comment]
Thanks for the feedback!
