### ISSUE TITLE
Angular 1.3.10

### ISSUE THREAD

**Issue by couchguy** [eggheadio/egghead-angularjs-from-scratch-getting-started#5]
This isn't really an issue, but the videos and code use angular 1.2.19 and the adding of bookmarks works create, but when you update to the current version of angular 1.3.10 it seems like the filter on ng-repeats acts a bit different and the new item doesn't show up on the screen. I was wonder what needs to change to get the adding to working correctly in the current version of angular

**Comment by joelhooks** [comment]
Updated master to 1.3
